<h1>Post Details</h1><br><br>
<div class="row">
    <div class="col"><b><h3>Id</h3></b></div>
    <div class="col"><b><h3>Post Title</h3></b></div>
    <div class="col"><b><h3>Description</h3></b></div>
    <div class="col"></div>
    <div class="col"></div>
</div>
<br><br>
<?php foreach($post as $post): ?>
    <div class="row">

        <div class="col">
            <h3><?= $this->escapeHtml($post->getId()); ?>  </h3>
        </div>

        <div class="col">
            <h3><?= $this->escapeHtml($post->getTitle()); ?></h3>
        </div>
        
        <div class="col">
            <h3><?= $this->escapeHtml($post->getDescription()); ?></h3>
        </div>

        <div class="col">
            <a href="/crud/edit/<?= $this->escapeHtml($post->getId()); ?> "><h3>Edit</h3></a>
        </div>

        <div class="col">
            <a href="/crud/delete/<?= $this->escapeHtml($post->getId()); ?> "><h3>Delete</h3></a>
        </div>
    </div>

<?php endforeach; ?>

<a href="/crud/add"><h3>Insert New Row</h3></a>
